version: '3.9'
services:
    react-dev:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: react-dev
        volumes:
            - ./app:/app
        working_dir: /app
        tty: true
        ports:
            - "3000:3000"
